[package]
name = "image_tagger"
version = "0.1.0"
edition = "2021"

[lib]
name = "image_tagger"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
